### ISSUE TITLE
I get some errors....

### ISSUE THREAD

**Issue by schroepfer** [skyYaga/netatmo-epaper#9]
Hello, i'm Jürgen from Germany. 

I am nearly new in PYTHON !
Runnin your netatmo-epaper.py gets this errors: (I think there are missing libs!?)

`(netpaper) juergen@raspiEpaper:~/netatmo-epaper $ python3 netatmo-epaper/netatmo-epaper.py

Traceback (most recent call last):

  File "/home/juergen/netatmo-epaper/netatmo-epaper/netatmo-epaper.py", line 5, in <module>

    from drawing import DisplayDrawer, DateTimeModel, NetatmoIndoorModel, NetatmoOutdoorModel

  File "/home/juergen/netatmo-epaper/netatmo-epaper/drawing.py", line 2, in <module>

    from PIL import Image, ImageDraw, ImageFont

  File "/home/juergen/netpaper/lib/python3.9/site-packages/PIL/Image.py", line 100, in <module>

    from . import _imaging as core

ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory

(netpaper) juergen@raspiEpaper:~/netatmo-epaper $`

**Comment by schroepfer** [comment]
PS:
the missing display, drawing are in the path:

`(netpaper) juergen@raspiEpaper:~/netatmo-epaper/netatmo-epaper $ ls -al
insgesamt 36

drwxr-xr-x  3 juergen juergen 4096  6. Aug 12:12 .

drwxr-xr-x 12 juergen juergen 4096  6. Aug 11:52 ..

-rw-r--r--  1 juergen juergen 1438  6. Aug 10:54 display.py

-rw-r--r--  1 juergen juergen 8122  6. Aug 10:54 drawing.py

-rw-r--r--  1 juergen juergen    0  6. Aug 10:54 __init__.py

-rw-r--r--  1 juergen juergen 4884  6. Aug 10:54 netatmo-epaper.py

drwxr-xr-x  2 juergen juergen 4096  6. Aug 11:38 __pycache__

-rw-r--r--  1 juergen juergen 2161  6. Aug 10:54 weather.py

(netpaper) juergen@raspiEpaper:~/netatmo-epaper/netatmo-epaper $`
